version: 2
registries:
  npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    replaces-base: true

updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - npmjs
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-development:
        dependency-type: development
      npm-production:
        dependency-type: production

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
